### ISSUE TITLE
Prepare image for SD card manufacturer to flash

### ISSUE THREAD

**Issue by kelada** [getsenic/senic-os#103]
~~With ethernet being disabled by default we don't have a way to update images without on boarding them, thus~~ the image we send to the manufacturer we need to make sure has the following issues resolved:
- [x] Move to single SD card image #91 
- [x] Fix bluetooth [#394](https://github.com/getsenic/senic-hub/issues/394)
- [x] Resolve security issues #93 
- [x] Add hardware testing scripts #77 
- [x] Setup production mender server https://github.com/getsenic/senic-infrastructure/issues/25

During the assembly process one of the follow solutions should be used to **trigger the test scripts and print the output to the serial console**.

#### Solution 1 (current)
Log into devices, run hardware scripts.

#### Solution 2
Modify the factory reset button on the hub.

#### Solution 3
Pull one of the GPIO pins to ground (via a jig).
