### ISSUE TITLE
Re-implement mender

### ISSUE THREAD

**Issue by kelada** [getsenic/senic-os#76]
### TODO
- [x] Move u-boot-senic to use default u-boot with appends
- [x] Apply mender u-boot patches (via auto patching or manually)
- [x] Configure application stack to to use /data partition
- [x] Test hosted mender service to send updates to devices
